# Generated by Django 3.0.3 on 2020-02-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='app',
            field=models.ManyToManyField(to='users.Apps'),
        ),
    ]
