# Generated by Django 3.0.3 on 2020-02-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='secret',
            field=models.CharField(default=1029384756, max_length=64),
            preserve_default=False,
        ),
    ]
